server {
    listen 80;
    server_name  localhost;

    root /usr/share/nginx/html;
    index index.html;
    # Serve static files directly
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Increase file upload size and buffer
    client_max_body_size 10M;
    sendfile on;
}
